### PR TITLE
Allow Sensor and Step Selection in Settings + Add import for beerxml, kbh and brewfather

### PR DESCRIPTION
**Pull request by avollkopf**
This will allow to select sensors and steps on the settings page.

I hesitated to add the npm build as I was fearing that this would caus issues for merging. But the npm build is running on my system

### CODE REVIEW

**Comment by JamFfm** [comment]
strange but this does not work in my setting.
Sensor is still a text field.
Used it in a new folder with original config.json.
Which kind of import did you use?
This is mine: 
`from cbpi.api.config import ConfigType`

**Comment by avollkopf** [comment]
@JamFfm with this pull request I uploaded only the changed js file. You need to build the package with npm before you can use it. This is for me a bit tricky as I could not get it to run on the pi, but in a ubuntu container on my NAS. Afterwards I copied it to my pi and the selection is working fine. I just dd not included it to the pull request as I was not sure, if github would mark those changes as a conflict for merging...

I can zip my package later and send you a link to downaload it for testing.

**Comment by JamFfm** [comment]
@avollkopf ah now i got it. I am not familiar with java script. It would be really great if you can send me the files. Thank you

**Comment by avollkopf** [comment]
Last commit will allow upload of xml and kbh2 files to an upload folder. 

-> changes in cbpi4 are required and will be also uploaded and pull request will be created

Screenshot 2021-05-22 085613

**Comment by avollkopf** [comment]
Recipe selection and creation from uploaded files now possible:
Screenshot 2021-05-25 204046

Added color property to led which allows selection of three different colors for led symbols individually
Screenshot 2021-05-26 184246
Screenshot 2021-05-26 184156

**Comment by avollkopf** [comment]
Last commit will allow to save the active recipe to the recipe book:
Screenshot 2021-05-27 200922
Screenshot 2021-05-27 201417

It will require also a commit on the server side:
https://github.com/Manuel83/craftbeerpi4/pull/80/commits/40020ba64d7d648bf56b93bd1352e9e4bc4accf8

**Comment by avollkopf** [comment]
Added delete function to Analytics page. Only changes in UI were required. Added function in index.js of charting that uses the clear log function from the logapi. It just cycles through the selected sensors and deletes the log files

Screenshot 2021-06-16 204758

**Comment by avollkopf** [comment]
All changes have been implemented with last commit

**Pull request closed without merging**
